package dev.aeroac.neural.telemetry;

/** Raw telemetry schema, NOT a model input list. Unknown values are NaN in memory / null in JSON. */
public enum FrameField {
    YAW, PITCH, DELTA_YAW, DELTA_PITCH, DELTA2_YAW, DELTA2_PITCH,
    ROTATION_SPEED, ROTATION_ACCELERATION, ROTATION_JERK,
    PLAYER_X, PLAYER_Y, PLAYER_Z, EYE_HEIGHT,
    VELOCITY_X, VELOCITY_Y, VELOCITY_Z,
    ON_GROUND, SPRINTING, SNEAKING, AIRBORNE,
    TARGET_PRESENT, TARGET_ENTITY_ID, PREVIOUS_TARGET_ENTITY_ID, TARGET_TYPE,
    TARGET_X, TARGET_Y, TARGET_Z, TARGET_VELOCITY_X, TARGET_VELOCITY_Y, TARGET_VELOCITY_Z,
    TARGET_MIN_X, TARGET_MIN_Y, TARGET_MIN_Z, TARGET_MAX_X, TARGET_MAX_Y, TARGET_MAX_Z,
    AIM_POINT_X, AIM_POINT_Y, AIM_POINT_Z, DISTANCE_TO_TARGET,
    TARGET_YAW, TARGET_PITCH, AIM_ERROR_YAW, AIM_ERROR_PITCH, AIM_ERROR_TOTAL,
    AIM_ERROR_DELTA, CROSSHAIR_INSIDE_HITBOX, LINE_OF_SIGHT,
    ATTACK, SWING, SUCCESSFUL_HIT, ATTACK_COUNT, SWING_COUNT, CANCELLED_ATTACK_COUNT,
    TICKS_SINCE_ATTACK, ATTACK_INTERVAL_MS, TARGET_SWITCH, TICKS_SINCE_TARGET_SWITCH,
    PING_MS, ESTIMATED_JITTER_MS, SERVER_TICK_DURATION_MS, CLIENT_PROTOCOL_VERSION,
    REACH_EVIDENCE, WALL_HIT_EVIDENCE, ENTITY_PIERCE_EVIDENCE, PACKET_ORDER_EVIDENCE,
    REACH_DISTANCE, REACH_TARGET_ENTITY_ID, REACH_OBSERVATION_AGE_MS,
    TELEPORT_STATE, VEHICLE_STATE, INVENTORY_STATE, HELD_ITEM_TYPE,
    MOVEMENT_HAS_POSITION, MOVEMENT_HAS_LOOK, SEGMENT_START, SAMPLE_INTERVAL_MS,
    TRANSACTION_ID, SERVER_TICK,
    /**
     * Raw schema 2. Degrees of rotation per mouse count on each axis, as Grim's AimProcessor
     * estimates the player's sensitivity grid; unknown until it has enough small rotations.
     */
    MOUSE_GRID_YAW, MOUSE_GRID_PITCH;

    public static final int COUNT = values().length;

    /** Raw schema version that introduced a field; frames of an older version carry it as unknown. */
    public int since() { return ordinal() >= MOUSE_GRID_YAW.ordinal() ? 2 : 1; }
}
